### ISSUE TITLE
No AndroidManifest.xml file

### ISSUE THREAD

**Issue by iamutkarshtiwari** [miptildar/AndroidCircleCamera#1]
Android Studio throw this error -

`Gradle 'AndroidCircleCamera' project refresh failed`

`Error:Cannot read packageName from /Users/lexluther/Documents/AndroidCircleCamera/app/src/main/AndroidManifest.xml`

**Comment by miptildar** [comment]
@iamutkarshtiwari  sorry, I fixed it and updated source code.
If you are looking for an Android camera library, take a look at [this project](https://github.com/CameraKit/camerakit-android)

My project - is for those who are going to implement camera on their own.
